repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  name: FaceBox

  description: description of repo

  homepage: https://example.github.io/

  private: false

  has_issues: true

  has_wiki: true

  has_downloads: true

  default_branch: develop

  allow_squash_merge: true

  allow_merge_commit: true

  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted

collaborators:

  - username: Tej780

    permission: push

  - username: VikashKothary

    permission: push
